project_id = "usapon-package-maker"

[functions.package-upload-box-asset]
verify_jwt = true

[functions.package-delete-box-project]
verify_jwt = true

[functions.package-delete-cloud-data]
verify_jwt = true

[functions.package-cleanup-box-assets]
verify_jwt = false

[functions.package-redeem-theme-pack]
verify_jwt = true
